#pragma once

#define CLEO_VERSION_MAIN    2
#define CLEO_VERSION_MAJOR   1
#define CLEO_VERSION_MINOR   0

#define CLEO_VERSION ((CLEO_VERSION_MAIN << 24)|(CLEO_VERSION_MAJOR << 16)|(CLEO_VERSION_MINOR << 8))

#define CLEO_VERSION_DOT CLEO_VERSION_MAIN.CLEO_VERSION_MAJOR.CLEO_VERSION_MINOR
#define CLEO_VERSION_COMMA CLEO_VERSION_MAIN,CLEO_VERSION_MAJOR,CLEO_VERSION_MINOR

#define __TO_STR(x) #x
#define TO_STR(x) __TO_STR(x)

#define CLEO_VERSION_DOT_STR TO_STR(CLEO_VERSION_DOT)
#define CLEO_VERSION_COMMA_STR TO_STR(CLEO_VERSION_COMMA)
